export const SET_USER_DATA = 'SET_USER_DATA';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const SET_QUESTIONNAIRES = 'SET_QUESTIONNAIRES';
export const SET_QUESTION_COUNT = 'SET_QUESTION_COUNT';
export const SET_QUESTION = 'SET_QUESTION';
export const SET_SELECTED_QUESTIONNARE = 'SET_SELECTED_QUESTIONNARE';
export const SET_QUESTIONNAIRE_TITLE = 'SET_QUESTIONNAIRE_TITLE';
